{% set version = "1.0.5" %}

package:
  name: hmmstr
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/73/eb/c2746191ab0de3153f1dbd40bf3d5547721bf6418b037fde17cd4e7f1356/HMMSTR-{{ version }}.tar.gz
  # You will need to replace the sha256 with the actual hash of your hmmstr package
  sha256: 2ece13b332cb86fc91ae0e66393b9ec757d19ed36cb2c7f38493ac2e34759436

build:
  number: 0
  script: "{{PYTHON}} -m pip install . --no-deps --ignore-installed --no-cache-dir --no-build-isolation -vv"
  

requirements:
  build:
    - {{ compiler('c') }}
    # - pkg-config
  host:
    - python
    - pkg-config
    - pip
    - cython
    - setuptools
    - wheel
    - libcxx  # For libc
    - glib    # For libglib-2.0
  run:
    - python
    - colorama
    - numpy 
    - pandas 
    - pickleshare
    - scikit-learn
    - scipy 
    - seaborn
    - importlib-resources
    - mappy
    - pysam

test:
  commands:
    - hmmstr --help
  # imports:
  #   - hmmstr

about:
  home: https://github.com/Boyle-Lab/HMMSTR
  license: MIT
  summary: "HMMSTR is a bioinformatics software package for calling tandem reapeat copy number from raw, long-read, sequencing reads."