{% set version = "1.0.4" %}

package:
  name: hmmstr
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/f7/6a/6a5b45146394a62fe8b45f160feabed36b53e5b71c89e0d41d82f8fd1e1e/HMMSTR-{{ version }}.tar.gz
  # You will need to replace the sha256 with the actual hash of your hmmstr package
  sha256: 8e3664370a910134465d72f1a3639af168aac1da56eb87f9765791fcd73ca326

build:
  number: 0
  script: "{{PYTHON}} -m pip install . --no-deps --ignore-installed --no-cache-dir --no-build-isolation -vv"
  

requirements:
  build:
    - {{ compiler('c') }}
    # - pkg-config
  host:
    - python
    - pkg-config
    - pip
    - cython
    - setuptools
    - wheel
    - libcxx  # For libc
    - glib    # For libglib-2.0
  run:
    - python
    - colorama
    - numpy 
    - pandas 
    - pickleshare
    - scikit-learn
    - scipy 
    - seaborn
    - importlib-resources
    - mappy
    - pysam

test:
  commands:
    - hmmstr --help
  # imports:
  #   - hmmstr

about:
  home: https://github.com/Boyle-Lab/HMMSTR
  license: MIT
  summary: "HMMSTR is a bioinformatics software package for calling tandem reapeat copy number from raw, long-read, sequencing reads."