{% set version = "1.0.2" %}

package:
  name: hmmstr
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/h/HMMSTR/HMMSTR-{{ version }}.tar.gz
  # You will need to replace the sha256 with the actual hash of your hmmstr package
  sha256: 428b3b6d4dba7740c3af13d094b907dc6556a7447240da959dbecdca2a687bde

build:
  number: 0
  script: "{{PYTHON}} -m pip install . --no-deps --ignore-installed --no-cache-dir --no-build-isolation -vv"
  

requirements:
  build:
    - {{ compiler('c') }}
    # - pkg-config
  host:
    - python
    - pkg-config
    - pip
    - cython
    - setuptools
    - wheel
    - libcxx  # For libc
    - glib    # For libglib-2.0
  run:
    - python
    - colorama
    - numpy 
    - pandas 
    - pickleshare
    - scikit-learn
    - scipy 
    - seaborn
    - importlib-resources
    - mappy
    - pysam

test:
  commands:
    - hmmstr --help
  # imports:
  #   - hmmstr

about:
  home: https://github.com/Boyle-Lab/HMMSTR
  license: MIT
  summary: "HMMSTR is a bioinformatics software package for calling tandem reapeat copy number from raw, long-read, sequencing reads."